"""Add user caps to make sure two usernames can't be the same

Revision ID: b0817150d20f
Revises: b1654316ff87
Create Date: 2021-04-22 16:02:55.796655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0817150d20f'
down_revision = 'b1654316ff87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_caps', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_user_caps'), 'users', ['user_caps'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_caps'), table_name='users')
    op.drop_column('users', 'user_caps')
    # ### end Alembic commands ###
