"""Add last updated to Note model

Revision ID: fca47933e1f8
Revises: b0817150d20f
Create Date: 2021-04-24 11:11:37.515698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca47933e1f8'
down_revision = 'b0817150d20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'last_updated')
    # ### end Alembic commands ###
